spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url: jdbc:postgresql://10.5.0.5:5432/forum?currentSchema=public&autoReconnect=true&useSSL=false
spring.datasource.username: wissace
spring.datasource.password: wissace2022
spring.datasource.driver-class-name: org.postgresql.Driver

spring.data.mongodb.authentication-database: admin
spring.data.mongodb.host: 10.5.0.8
spring.data.mongodb.port: 27017
spring.data.mongodb.database: admin
spring.data.mongodb.username: wissace
spring.data.mongodb.password: wissace2022
spring.data.mongodb.auto-index-creation: true